"""
Django settings for reviewer project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Use PyMySQL as MySQL adapter for Django
try:
    import pymysql

    pymysql.install_as_MySQLdb()
except ImportError:
    pass  # PyMySQL not installed, SQLite will be used

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# Check if running on Toolforge (set via environment variable)
IS_TOOLFORGE = os.environ.get("IS_TOOLFORGE", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
if IS_TOOLFORGE:
    SECRET_KEY = os.environ.get(
        "DJANGO_SECRET_KEY",
        "django-insecure-xs^j(8v6+dxl01-37si+&q*msl6c&qu!-5aj0aso7ov8i(%5lr",
    )
    DEBUG = False
    ALLOWED_HOSTS = [
        "pendingchangesbot.toolforge.org",
        ".toolforge.org",
    ]
else:
    SECRET_KEY = "django-insecure-xs^j(8v6+dxl01-37si+&q*msl6c&qu!-5aj0aso7ov8i(%5lr"  # noqa: S105
    DEBUG = True
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "reviews",
    "review_statistics",
    "bot_control",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "csp.middleware.CSPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "bot_control.middleware.AuditLogMiddleware",
]

ROOT_URLCONF = "reviewer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "reviewer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if IS_TOOLFORGE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "s57224__pendingchangesbot",
            "HOST": "tools.db.svc.wikimedia.cloud",
            "OPTIONS": {
                "read_default_file": os.path.expanduser("~/replica.my.cnf"),
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
                "charset": "utf8mb4",
            },
        }
    }

    # CSRF trusted origins for Toolforge
    CSRF_TRUSTED_ORIGINS = [
        "https://pendingchangesbot.toolforge.org",
    ]

    # Secure cookie settings for production
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

else:
    # Local development database (SQLite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Static files collection for production
STATIC_ROOT = os.getenv("STATIC_ROOT", BASE_DIR / "staticfiles")

# WhiteNoise configuration for efficient static file serving
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Content Security Policy - Allow external CDNs for scripts and styles
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "'unsafe-eval'",  # Required for Vue.js
    "https://tools-static.wmflabs.org",
    "*.toolforge.org",
    "*.wikimedia.org",
    "*.wikipedia.org",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://tools-static.wmflabs.org",
    "*.toolforge.org",
    "*.wikimedia.org",
    "*.wikipedia.org",
)
CSP_CONNECT_SRC = (
    "'self'",
    "*.toolforge.org",
    "*.wikimedia.org",
    "*.wikipedia.org",
)
CSP_IMG_SRC = ("'self'", "data:", "https:", "*.wikimedia.org", "*.wikipedia.org")
CSP_FONT_SRC = ("'self'", "data:", "https://tools-static.wmflabs.org")

PYWIKIBOT_SITE_FAMILY = os.getenv("PYWIKIBOT_SITE_FAMILY", "wikipedia")

# ORES model thresholds (global defaults, per-wiki config takes precedence)
ORES_DAMAGING_THRESHOLD = float(os.getenv("ORES_DAMAGING_THRESHOLD", "0.3"))
ORES_GOODFAITH_THRESHOLD = float(os.getenv("ORES_GOODFAITH_THRESHOLD", "0.7"))
ORES_DAMAGING_THRESHOLD_LIVING = float(os.getenv("ORES_DAMAGING_THRESHOLD_LIVING", "0.1"))
ORES_GOODFAITH_THRESHOLD_LIVING = float(os.getenv("ORES_GOODFAITH_THRESHOLD", "0.9"))

# Revert detection configuration
# Enable/disable revert detection for already-reviewed edits
ENABLE_REVERT_DETECTION = os.getenv("ENABLE_REVERT_DETECTION", "True").lower() in (
    "true",
    "1",
    "yes",
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
