# Generated by Django 4.2.25 on 2026-01-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('process_id', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bot Status',
                'verbose_name_plural': 'Bot Statuses',
                'db_table': 'bot_status',
            },
        ),
    ]
