# Generated by Django 4.2.25 on 2026-02-10 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_code', models.CharField(max_length=20)),
                ('page_id', models.IntegerField()),
                ('page_title', models.CharField(max_length=500)),
                ('revision_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(choices=[('approve', 'Approved'), ('blocked', 'Blocked'), ('manual', 'Manual Review Required')], max_length=20)),
                ('decision_label', models.CharField(blank=True, max_length=100)),
                ('decision_reason', models.TextField(blank=True)),
                ('determining_check', models.CharField(blank=True, max_length=100)),
                ('total_checks_run', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_dry_run', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot Activity',
                'verbose_name_plural': 'Bot Activities',
                'db_table': 'bot_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='bot_activit_created_5131e6_idx'), models.Index(fields=['wiki_code', '-created_at'], name='bot_activit_wiki_co_74cffc_idx'), models.Index(fields=['decision'], name='bot_activit_decisio_b2da20_idx')],
            },
        ),
    ]
