# Generated by Django 4.2.25 on 2026-03-02 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bot_control", "0002_add_bot_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=2048)),
                ("status_code", models.IntegerField()),
                ("username", models.CharField(default="anonymous", max_length=255)),
                ("role", models.CharField(default="public", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("query_params", models.TextField(blank=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_log_timesta_8b04a8_idx"
                    ),
                    models.Index(fields=["method"], name="audit_log_method_8fed6f_idx"),
                    models.Index(
                        fields=["status_code"], name="audit_log_status__90f089_idx"
                    ),
                    models.Index(
                        fields=["username", "-timestamp"],
                        name="audit_log_usernam_cd96e7_idx",
                    ),
                    models.Index(
                        fields=["path", "-timestamp"], name="audit_log_path_5924d8_idx"
                    ),
                ],
            },
        ),
    ]
