# Generated by Django 4.2.25 on 2026-02-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flaggedrevsstatistics',
            index=models.Index(fields=['wiki', '-date'], name='reviews_fla_wiki_id_76017c_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedrevsstatistics',
            index=models.Index(fields=['date'], name='reviews_fla_date_cb4f30_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewactivity',
            index=models.Index(fields=['wiki', '-date'], name='reviews_rev_wiki_id_caed95_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewactivity',
            index=models.Index(fields=['date'], name='reviews_rev_date_8a2329_idx'),
        ),
    ]
